server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:~/url_shortener
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: 0.0.0.0
      port: 6379
